### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by hymerman** [Arachnid/bloggart#35]
I thought I'd give bloggart another go now that the last issue I opened has been fixed. Same steps as before;

git clone git://github.com/Arachnid/bloggart.git
git submodule init
git submodule update

"Run" using Google AppEngine Launcher
Visit http://localhost:8080

Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 3177, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 3120, in _Dispatch
    base_env_dict=env_dict)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 515, in Dispatch
    base_env_dict=base_env_dict)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2379, in Dispatch
    self._module_dict)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2289, in ExecuteCGI
    reset_modules = exec_script(handler_path, cgi_path, hook)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2185, in ExecuteOrImportScript
    exec module_code in script_module.__dict__
  File "D:\somewhere\bloggart\static.py", line 21, in <module>
    ROOT_ONLY_FILES = ['/robots.txt','/' + config.google_site_verification]
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by Arachnid** [comment]
You need to edit config.py with your config settings before running it.

**Comment by hymerman** [comment]
Yep, that fixed it. May I suggest replacing the 'None' with '' to prevent this confusion for others in future?

**Comment by Arachnid** [comment]
Actually, the correct fix would be to exclude that path from 'ROOT_ONLY_FILES' if the relevant config variable isn't set.

**Comment by ghost** [comment]
small fix for this http://github.com/hickups/bloggart/commit/3ae402c79e98871b035aee159425eb71c4c486f4

**Comment by Arachnid** [comment]
Fixed by hickups.
