### ISSUE TITLE
sitemap traceback

### ISSUE THREAD

**Issue by zlouattara** [Arachnid/bloggart#42]
AttributeError: 'module' object has no attribute 'google_sitemap_ping'

**Comment by Arachnid** [comment]
...can you give more details? When does this occur? What version of bloggart are you running? What's the actual traceback?

**Comment by zlouattara** [comment]
###COMMENT
This is all happening when the /_ah/queue/deferred task runs. it gets a 500 error

```
  03-22 07:55AM 53.587 /_ah/queue/deferred 500 156ms 310cpu_ms 251api_cpu_ms 0kb AppEngine-Google; (+http://code.google.com/appengine)
  See details

  0.1.0.2 - - [22/Mar/2010:07:55:53 -0700] "POST /_ah/queue/deferred HTTP/1.1" 500 124 "http://dev.latest.ouattaracloud.appspot.com/_ah/queue/deferred" "AppEngine-Google; (+http://code.google.com/appengine)" "dev.latest.ouattaracloud.appspot.com"
```

###INFO
      I 03-22 07:55AM 53.592

```
  X-Appengine-Taskretrycount:35, X-Appengine-Queuename:default, X-Appengine-Taskname:sitemap-201003211804
```

###ERROR
      E 03-22 07:55AM 53.739

```
  'module' object has no attribute 'google_sitemap_ping'
  Traceback (most recent call last):
    File "/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 509, in __call__
      handler.post(*groups)
    File "/base/python_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 256, in post
      run(self.request.body)
    File "/base/python_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 124, in run
      return func(*args, **kwds)
    File "/base/data/home/apps/ouattaracloud/dev.340659675845788505/utils.py", line 91, in _regenerate_sitemap
      if config.google_sitemap_ping:
  AttributeError: 'module' object has no attribute 'google_sitemap_ping'
```

**Comment by Arachnid** [comment]
It looks like you updated your copy of bloggart without merging in configuration file changes. Add the following line to your config.py:

```
google_sitemap_ping = False
```

**Comment by zlouattara** [comment]
thanks nick! i think that will do. see you at i/o!
